version: "3.9"
services:
  # MySQL 8 環境
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      # 初期化SQLスクリプトをマウント
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  # PostgreSQL 16 環境
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Oracle XE 21c 環境
  # Oracleの公式イメージはDocker Hubに存在しないため、gvenzlのイメージを使用
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - ./oracle/init.sql:/container-entrypoint-initdb.d/init.sql
