BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    date_of_birth DATE DEFAULT NULL,
    gender VARCHAR2(30) DEFAULT 'prefer_not_to_say',
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    last_login_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- テーブルコメント
COMMENT ON TABLE users IS 'ユーザー情報を格納するテーブル';

-- カラムコメント
COMMENT ON COLUMN users.id IS 'ユーザーID（自動採番）';
COMMENT ON COLUMN users.username IS 'ユーザー名（ユニーク）';
COMMENT ON COLUMN users.email IS 'メールアドレス（ユニーク）';
COMMENT ON COLUMN users.password_hash IS 'ハッシュ化されたパスワード';
COMMENT ON COLUMN users.date_of_birth IS '生年月日';
COMMENT ON COLUMN users.gender IS '性別';
COMMENT ON COLUMN users.is_active IS 'アカウント有効状態（1: 有効, 0: 無効）';
COMMENT ON COLUMN users.last_login_at IS '最終ログイン日時';
COMMENT ON COLUMN users.created_at IS '作成日時';
COMMENT ON COLUMN users.updated_at IS '更新日時';

